import { RootAnimationLayout } from '@/layouts/RootAnimationLayout'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Cozy Home',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="vn">
			<body className={montserrat.className}>
				<main>
					<RootAnimationLayout >
						{children}
					</RootAnimationLayout>
				</main>
				<footer className='center mt-5 flex justify-center space-x-4 bg-[#E7E8EF] p-4 text-xs'>
					<p>Copyright © 2023 Cozy Home</p>
				</footer>
			</body>
		</html>
	)
}
